nano: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/first-interactions@v1
        with:
          repo-token: ${{secret.GITHUB_TOKEN }}
          pre-message:
              ~K Thanks for opening your first pull request!
             We're happy to have your contribution. Let us know if you need any help!
